### ISSUE TITLE
DownloadFile not working for first time on click of download button

### ISSUE THREAD

**Issue by ajinkya976** [ammarptn/GDrive-Rest-Android#11]
Hi,

when i click on download file button first time it is not working (not downloading file from google drive)

When i click button second or sometimes on third time the file is getting downloaded.

when i install app first time and clicks on download button ***downoadFile()*** method gets call also i am getting ***fileId*** but the code is going to ***addOnFailureListener***. i am getting  ***failed Restored...*** toast for first time.

When i click second time download button the file is getting downloaded sometimes not even on second attempt but gets download on third attempt.

below is my code
```
 public void downoadFile()
    {
        if (mDriveServiceHelper != null) {
            Log.d(TAG, "Querying for files.");

            mDriveServiceHelper.queryFiles()
                    .addOnSuccessListener(fileList -> {
                        for (com.google.api.services.drive.model.File file : fileList.getFiles()) {

                            fileName=file.getName();

                            if(fileName.equals("cards_db"))
                            {
                                fileId=file.getId();

                                mDriveServiceHelper.downloadFile(new File("/data/data/com.cards.mycards/databases/cards_db"), fileId)
                                        .addOnSuccessListener(new OnSuccessListener<Void>() {
                                            @Override
                                            public void onSuccess(Void aVoid) {
                                                Toast.makeText(MainActivity.this, "Data Restored...", Toast.LENGTH_SHORT).show();
                                            }
                                        })
                                        .addOnFailureListener(new OnFailureListener() {
                                            @Override
                                            public void onFailure(@NonNull Exception e) {
					Toast.makeText(MainActivity.this, "failed Restored...", Toast.LENGTH_SHORT).show();
                                            }
                                        });
                            }

                        }
                        // String fileNames = builder.toString();

                    })
                    .addOnFailureListener(exception -> Log.e(TAG, "Unable to query files.", exception));
        }


    }


 public Task<Void> downloadFile(java.io.File targetFile, String fileId) {
        return Tasks.call(mExecutor, () -> {
            // Retrieve the metadata as a File object.
            OutputStream outputStream = new FileOutputStream(targetFile);
            mDriveService.files().get(fileId).executeMediaAndDownloadTo(outputStream);
            return null;
        });
    }
```

can you please help me in knowing what might be causing this.

Thanks in advanced.

**Comment by ammarptn** [comment]
> Hi,
> 
> when i click on download file button first time it is not working (not downloading file from google drive)
> 
> When i click button second or sometimes on third time the file is getting downloaded.
> 
> when i install app first time and clicks on download button _**downoadFile()**_ method gets call also i am getting _**fileId**_ but the code is going to _**addOnFailureListener**_. i am getting _**failed Restored...**_ toast for first time.
> 
> When i click second time download button the file is getting downloaded sometimes not even on second attempt but gets download on third attempt.
> 
> below is my code
> 
> ```
>  public void downoadFile()
>     {
>         if (mDriveServiceHelper != null) {
>             Log.d(TAG, "Querying for files.");
> 
>             mDriveServiceHelper.queryFiles()
>                     .addOnSuccessListener(fileList -> {
>                         for (com.google.api.services.drive.model.File file : fileList.getFiles()) {
> 
>                             fileName=file.getName();
> 
>                             if(fileName.equals("cards_db"))
>                             {
>                                 fileId=file.getId();
> 
>                                 mDriveServiceHelper.downloadFile(new File("/data/data/com.cards.mycards/databases/cards_db"), fileId)
>                                         .addOnSuccessListener(new OnSuccessListener<Void>() {
>                                             @Override
>                                             public void onSuccess(Void aVoid) {
>                                                 Toast.makeText(MainActivity.this, "Data Restored...", Toast.LENGTH_SHORT).show();
>                                             }
>                                         })
>                                         .addOnFailureListener(new OnFailureListener() {
>                                             @Override
>                                             public void onFailure(@NonNull Exception e) {
> 					Toast.makeText(MainActivity.this, "failed Restored...", Toast.LENGTH_SHORT).show();
>                                             }
>                                         });
>                             }
> 
>                         }
>                         // String fileNames = builder.toString();
> 
>                     })
>                     .addOnFailureListener(exception -> Log.e(TAG, "Unable to query files.", exception));
>         }
> 
> 
>     }
> 
> 
>  public Task<Void> downloadFile(java.io.File targetFile, String fileId) {
>         return Tasks.call(mExecutor, () -> {
>             // Retrieve the metadata as a File object.
>             OutputStream outputStream = new FileOutputStream(targetFile);
>             mDriveService.files().get(fileId).executeMediaAndDownloadTo(outputStream);
>             return null;
>         });
>     }
> ```
> 
> can you please help me in knowing what might be causing this.
> 
> Thanks in advanced.

The code look fine, the issues that it not trigger the download function might cause of "mDriveServiceHelper " is null

for the error in "addOnFailureListener", please check the message from exception object to see the real cause. Display only toast or log with your custom message will not help debug anything

**Comment by ajinkya976** [comment]
Hi ammar,

I putted try catch in below method and i think i found the error.
```
public Task<Void> downloadFile(java.io.File targetFile, String fileId) {
        return Tasks.call(mExecutor, () -> {
            // Retrieve the metadata as a File object.

            try{
            OutputStream outputStream = new FileOutputStream(targetFile);
            mDriveService.files().get(fileId).executeMediaAndDownloadTo(outputStream);
}catch(exception e)
{
e.printstacktrace();
}
            return null;
        });
    }
```

the error is first time when i download the file ***/data/data/com.cards.mycards/databases/cards_db*** this path is not present thats why it is not downloading file and going to ***addOnFailureListener***

can you please me help to check if (***/data/data/com.cards.mycards/databases/cards_db***) directory is not present then create directory.

**Comment by ammarptn** [comment]
> Hi ammar,
> 
> I putted try catch in below method and i think i found the error.
> 
> ```
> public Task<Void> downloadFile(java.io.File targetFile, String fileId) {
>         return Tasks.call(mExecutor, () -> {
>             // Retrieve the metadata as a File object.
> 
>             try{
>             OutputStream outputStream = new FileOutputStream(targetFile);
>             mDriveService.files().get(fileId).executeMediaAndDownloadTo(outputStream);
> }catch(exception e)
> {
> e.printstacktrace();
> }
>             return null;
>         });
>     }
> ```
> 
> the error is first time when i download the file, _**/data/data/com.cards.mycards/databases/cards_db**_ this path is not present in device internal storage. thats why it is going to _**addOnFailureListener**_
> 
> can you please me help to check if (_**/data/data/com.cards.mycards/databases/cards_db**_) directory is not present in internal storage then create directory.

here is the solution
https://stackoverflow.com/questions/28947250/create-a-directory-if-it-does-not-exist-and-then-create-the-files-in-that-direct

**Comment by ajinkya976** [comment]
Hi Amar,

That code is not helping me. 

```
if (! directory.exists()){
        directory.mkdir();
        // If you require it to make the entire directory path including parents,
        // use directory.mkdirs(); here instead.
    }
```

actually my app is storing some data in sqlite DB.

I am backing up that database to google drive but now when i am downloading that DB from drive since folder path is not present in internal storage to keep the DB file it is giving below error.

```
W/System.err: java.io.FileNotFoundException: /data/data/com.cards.mycards/databases (Is a directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:308)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
        at com.cards.mycuecards.DriveServiceHelper.lambda$downloadFile$9$DriveServiceHelper(DriveServiceHelper.java:376)
        at com.cards.mycuecards.-$$Lambda$DriveServiceHelper$BlWDiQe-GUpOGeVzO1ypMa-ntwU.call(Unknown Source:6)
        at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
I/Toast: Show toast from OpPackageName:com.cards.
```

can you please help on this ?

**Comment by ajinkya976** [comment]
i have resolved this issue getparentfile()
