### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by abharna** [ammarptn/GDrive-Rest-Android#13]
only buttons are created,not working any single button functions

**Comment by ammarptn** [comment]
Did you follow this instruction?

```
Step 3. Add OAuth 2.0 client IDs at Google API console

Step 4. Enable Google Drive API in Google API console

Step 5. Add "../auth/drive" in Scopes for Google APIs

Optional Step 6. Add "../auth/drive.appdata" in Scopes if you want to access application data folder
```

**Comment by abharna** [comment]
ss i follow those instruction

**Comment by frankyxcs** [comment]
first you should have some respect and say "thank you" to the author for this good library and not only claming not working ...not working ....
incredible ...
Learning by doing men . not only grabbing without knowing anything. 

everything is working fine. Just follow the instructions and add all dependencies. Enable drive api and it is much more easier to add this to the firebase console too
