### ISSUE TITLE
how to search in  sharedwithme

### ISSUE THREAD

**Issue by gauravgupta566** [ammarptn/GDrive-Rest-Android#16]
How to search folder and download file from sharedwithme folder

Thanks in advance

**Comment by ammarptn** [comment]
currently my code not yet support search on the "sharewithme" folder
but you can fork and add/edit search function to this

```java
public Task<List<GoogleDriveFileHolder>> searchFile(final String fileName, final String mimeType) {
        return Tasks.call(mExecutor, new Callable<List<GoogleDriveFileHolder>>() {
            @Override
            public List<GoogleDriveFileHolder> call() throws Exception {
                List<GoogleDriveFileHolder> googleDriveFileHolderList = new ArrayList<>();
               
                FileList result = mDriveService.files().list()
                        .setQ("name = '" + fileName + "' and mimeType ='" + mimeType + "'")
                        .setSpaces("drive")
                        .setIncludeTeamDriveItems(true) // <--- add this line
                        .setFields("files(id, name,size,createdTime,modifiedTime,starred)")
                        .execute();


                for (int i = 0; i < result.getFiles().size(); i++) {
                    GoogleDriveFileHolder googleDriveFileHolder = new GoogleDriveFileHolder();
                    googleDriveFileHolder.setId(result.getFiles().get(i).getId());
                    googleDriveFileHolder.setName(result.getFiles().get(i).getName());
                    googleDriveFileHolder.setModifiedTime(result.getFiles().get(i).getModifiedTime());
                    googleDriveFileHolder.setSize(result.getFiles().get(i).getSize());
                    googleDriveFileHolderList.add(googleDriveFileHolder);

                }

                return googleDriveFileHolderList;
            }
        });
    }
```

more info at : https://developers.google.com/drive/api/v3/enable-shareddrives#search_for_content_on_a_shared_drive

**Comment by gauravgupta566** [comment]
your code will work for Gsuite Email Id?

your code working perfectly with personal ID but not working for Gsuite Email Id

**Comment by ammarptn** [comment]
> your code will work for Gsuite Email Id?
> 
> your code working perfectly with personal ID but not working for Gsuite Email Id

It work with Gsuite Email 

but if you want to access share drive, I believe you have to submit your app to Google for reviewing first.
you can submit for review in the Google API console.

![image](https://user-images.githubusercontent.com/4441622/93736729-cbae5700-fc13-11ea-9a38-8e2548d23e18.png)

**Comment by gauravgupta566** [comment]
okay , 1 more question, could not do  to search folder but when i create folder with app then it is searchable. otherwise not

only those folder will searchable which is created by this app. if any any folder exist or create from gmail drive option using browser then we can't search that folder

**Comment by ammarptn** [comment]
> okay , 1 more question, could not do to search folder but when i create folder with app then it is searchable. otherwise not
> 
> only those folder will searchable which is created by this app. if any any folder exist or create from gmail drive option using browser then we can't search that folder

Google determined all data that not create from the app (even it on your google drive) are sensitive. 
Without verification. you will limited to the file that your app upload/create.

It Google policy and beyond my control. 
more info at : https://support.google.com/cloud/answer/9110914

by the way, you can checkout this lib https://github.com/ammarptn/GDriveDebugViewer
it will help you to testing upload/create/delete or browse the google drive while the app not yet verify.

**Comment by gauravgupta566** [comment]
**How to get shareable link while uploading file to drive?**

getting error
```
 val mutableList = mutableListOf<Permission>()
                 val permission=Permission()
                permission.role="reader"
                permission.type="anyone"
                permission.emailAddress="gupta.gaurav1@thinksys.com"
                mutableList.add(permission)


                val metadata =
                    com.google.api.services.drive.model.File()
                        .setParents(root)
                        .setMimeType(mimeType)
                        .setName(localFile.name)
                        .setPermissions(mutableList)
                        .setWebContentLink(System.currentTimeMillis().toString())
```



Thanks in Advance
