### ISSUE TITLE
How to upload image file to different google driver with email, password

### ISSUE THREAD

**Issue by sontn15** [ammarptn/GDrive-Rest-Android#17]
Hi you,
In my android app, i want to send image to special google driver (not in my phone) using by email, password.

Example: 
The google driver account target i want to send: email: abc@gmail.com, pass 123
In app, i choose image then i send to above email.

How to send it, please help me!

**Comment by ammarptn** [comment]
Hi,
In this case, I suggest you to have a relay server that perform uploading to your special google drive instead.
Ex: mobile app send image to server then the server upload to google drive.

Upload image to google drive account that not in your phone directly seem not possible and not advisable.

more info about server upload file at : https://developers.google.com/drive/api/v3/manage-uploads#node.js

**Comment by sontn15** [comment]
Can I send image file from my android app to public folder in google drive?

**Comment by ammarptn** [comment]
> Can I send image file from my android app to public folder in google drive?

if the drive owner share the drive with your account, then it be possible.

more info at : https://developers.google.com/drive/api/v3/enable-shareddrives

**Comment by sontn15** [comment]
Anyone allow upload to public folder google driver?

I have 10 users and 10 users will upload image to public folder google driver. 

Number of users can dynamic

**Comment by ammarptn** [comment]
not anyone, drive owner need to share an folder access to the user first.

**Comment by sontn15** [comment]
Thank you :(
