### ISSUE TITLE
Not sign in google when using different computer with SHA1...

### ISSUE THREAD

**Issue by sontn15** [ammarptn/GDrive-Rest-Android#18]
Hi you, please help me.

1. I want to upload image to google driver. When i call uploadFile with folderId, my image created in folder. But my image still created in my driver. How do I must to only upload file in folder by folderId and not upload file to my driver?

2. I created my project and get SHA1 with google api... in Laptop A. I can sign in google in android app. OK
But when I using Laptop B and building android app, I cant sign in google. I dont know fix problem. Please help me
When I call, resultCode = RESULT_CANCELED 

GoogleSignInClient mGoogleSignInClient = ResourceUtils.buildGoogleSignInClient(MainActivity.this);
startActivityForResult(mGoogleSignInClient.getSignInIntent(), Const.REQUEST_CODE_SIGN_IN_MAIN);

**Comment by ammarptn** [comment]
1. May I know, what you mean "driver"? 

2. Different Laptop will have different SHA1. You can create keystore and put SHA1 of that keystore in the google api console. Then share that keystore to other laptop and use that to sign the APK file.

> Hi you, please help me.
> 
> 1. I want to upload image to google driver. When i call uploadFile with folderId, my image created in folder. But my image still created in my driver. How do I must to only upload file in folder by folderId and not upload file to my driver?
> 2. I created my project and get SHA1 with google api... in Laptop A. I can sign in google in android app. OK
>    But when I using Laptop B and building android app, I cant sign in google. I dont know fix problem. Please help me
>    When I call, resultCode = RESULT_CANCELED
> 
> GoogleSignInClient mGoogleSignInClient = ResourceUtils.buildGoogleSignInClient(MainActivity.this);
> startActivityForResult(mGoogleSignInClient.getSignInIntent(), Const.REQUEST_CODE_SIGN_IN_MAIN);

1. May I know, what you mean "driver"? 

2. Different Laptop will have different SHA1. You can create keystore and put SHA1 of that keystore in the google api console. Then share that keystore to other laptop and use that to sign the APK file.

**Comment by ammarptn** [comment]
> Hi you, please help me.
> 
> 1. I want to upload image to google driver. When i call uploadFile with folderId, my image created in folder. But my image still created in my driver. How do I must to only upload file in folder by folderId and not upload file to my driver?
> 2. I created my project and get SHA1 with google api... in Laptop A. I can sign in google in android app. OK
>    But when I using Laptop B and building android app, I cant sign in google. I dont know fix problem. Please help me
>    When I call, resultCode = RESULT_CANCELED
> 
> GoogleSignInClient mGoogleSignInClient = ResourceUtils.buildGoogleSignInClient(MainActivity.this);
> startActivityForResult(mGoogleSignInClient.getSignInIntent(), Const.REQUEST_CODE_SIGN_IN_MAIN);

1. May I know, what you mean "driver"? 

2. Different Laptop will have different SHA1. You can create keystore and put SHA1 of that keystore in the google api console. Then share that keystore to other laptop and use that to sign the APK file.

**Comment by sontn15** [comment]
1. FolderId of different User, not folder of me.
I want upload image to folder, but i dont want create in my driver

2. Thank you, i will do by your solution. You can send me example or link

**Comment by ammarptn** [comment]
> 1. FolderId of different User, not folder of me.
>    I want upload image to folder, but i dont want create in my driver
> 2. Thank you, i will do by your solution. You can send me example or link

1. So other user drive already share with our google drive account? 
I'm not sure that if you want to upload file to other people drive, I think it require to submit the app to Google for verification first... 

2. here is the example : https://stackoverflow.com/questions/18328730/how-to-create-a-release-signed-apk-file-using-gradle. 
- create keystore
- get SHA1 from that keystore and put in Google API console
- make sure every time, every laptop, you create APK with that keystore.

**Comment by sontn15** [comment]
Yes, I did it successfully! Thankyou!

W/GetToken: [GetToken]GetToken failed with status code: NeedPermission
W/Auth: [GoogleAuthUtil] GoogleAuthUtil

I'm using login account_1, I can push image to folder in driver success. But when I choose account_2 I don't upload image to folder. I login success and using DriveServiceHelper.uploadFile. GoogleSignInAccount not null (mAccountGoogle.isExpired() = false)

please help me

**Comment by sontn15** [comment]
Exception when call uploadFire in addOnFailureListener

com.google.api.client.googleapis.extensions.android.gms.auth.UserRecoverableAuthIOException

**Comment by sontn15** [comment]
Hi, thank you for support!

When exception in uploadFile I will fix it,

 myActivity.startActivityForResult(
          exception.getIntent(), MyActivity.REQUEST_AUTHORIZATION);

The bug is close!
