### ISSUE TITLE
Is this library and sample app still valid/working?

### ISSUE THREAD

**Issue by RohitSurwase** [ammarptn/GDrive-Rest-Android#19]
When I run the sample app, I do not see any dialog which requests access to scope. After launching the app, I could see account chooser app but on click of that, nothing happens, no dialog to request scope as written in code. What could be the issue/fix?

**Comment by ammar-tesco** [comment]
> When I run the sample app, I do not see any dialog which requests access to scope. After launching the app, I could see account chooser app but on click of that, nothing happens, no dialog to request scope as written in code. What could be the issue/fix?

-  Add OAuth 2.0 client IDs at Google API console
-  Enable Google Drive API in Google API console
-  Add "../auth/drive" in Scopes for Google APIs

**Comment by RohitSurwase** [comment]
Nope, I have not integrated the library in my app. I am just trying the sample app. The sample app present in this repo does not show request scope dialog.

**Comment by ammar-tesco** [comment]
> Nope, I have not integrated the library in my app. I am just trying the sample app. The sample app present in this repo does not show request scope dialog.

You also need to do this on sample app as well with your google account, It is not a good practice for me to allow anyone who use sample app and connect to Google API with my account. Someone might abuse the sample app and cause issues on my Google account. (Eg. use my sample app to phishing anyone and access their google drive)

**Comment by ammar-tesco** [comment]
Anyhow, the debug keystore on my laptop will not be the same as your laptop. It will not show the scope dialog anyway if the keystore not matched. If you want to test, you need to use set your debug keystore on the Google API Console.

**Comment by RohitSurwase** [comment]
Why would/should it access your Google Drive? Suppose I am developing an app where user can access/manage their G Drive then it should not access my G Drive. On top of that it should not require user to enable some APIs on any console. Isn't the way it should work? Am I missing something?

**Comment by ammar-tesco** [comment]
> Why would/should it access your Google Drive? Suppose I am developing an app where user can access/manage their G Drive then it should not access my G Drive. On top of that it should not require user to enable some APIs on any console. Isn't the way it should work? Am I missing something?

What I mean is Google account on my Google API console, not my google drive.
The app's developer/ app's owner are the one who need to enable some API on the Google API console.
Users are not related in any of this part.

For example, if you want to use Google API, then you need to ask Google for your own API Key, not my

**Comment by RohitSurwase** [comment]
Sorry but I still don't get it. The library is your product that you are offering. The sample app is the example of its implementation. Yes I agree, as a developer one has to generate API keys based on keystore and enable respective libraries. Also, these API keys are not stored in app/source-code, Google maps it based on package name and signature. So why do I need to enable some APIs for sample app. The sample app should work like an app present on Play Store, right?
Thanks for replying.

**Comment by ammar-tesco** [comment]
> Sorry but I still don't get it. The library is your product that you are offering. The sample app is the example of its implementation. Yes I agree, as a developer one has to generate API keys based on keystore and enable respective libraries. Also, these API keys are not stored in app/source-code, Google maps it based on package name and signature. So why do I need to enable some APIs for sample app. The sample app should work like an app present on Play Store, right?
> Thanks for replying.

Google Drive API is more sensitive than Google Map API, 

I understand that you just want a convenient way to run the sample app and check the flow of how it work.
but it also risky for me as well if anyone abuse the sample app. So I choose not to.
The only solution to run the sample app is you need to config it with your keystore signature.

**Comment by RohitSurwase** [comment]
Ok, so I have created
1. A new project on Firebase Console.
2. Selected same project on Google Console
3. Enabled Drive API
4. Edited app on 'OAuth consent screen' and added/selected auth/drive scope. Added an email of myself as tester.
5. Added new OAuth 2.0 client ID with package name and debug sha1.

Now I am getting a dialog after selecting the Google Account but it just white/blank screen with progress on top. What could have been wrong?

**Comment by RohitSurwase** [comment]
In case of Authorized domain, I have not changed the auto filled domain name. It is projectId.firebaseapp.com.

**Comment by ammar-tesco** [comment]
> Ok, so I have created
> 
> 1. A new project on Firebase Console.
> 2. Selected same project on Google Console
> 3. Enabled Drive API
> 4. Edited app on 'OAuth consent screen' and added/selected auth/drive scope. Added an email of myself as tester.
> 5. Added new OAuth 2.0 client ID with package name and debug sha1.
> 
> Now I am getting a dialog after selecting the Google Account but it just white/blank screen with progress on top. What could have been wrong?

can you attached a screenshot?

**Comment by RohitSurwase** [comment]
Yes sure:
![20210116_160156](https://user-images.githubusercontent.com/22326509/104809562-45e29700-5814-11eb-8d05-93a7309675f4.jpg)

**Comment by RohitSurwase** [comment]
@ammar-tesco any update on the above issue?

**Comment by ammar-tesco** [comment]
> @ammar-tesco any update on the above issue?

![image](https://user-images.githubusercontent.com/76982427/104860632-e80e9600-595e-11eb-8ed0-62aed4a3801e.png)
check your logcat, it should tell you what is the issues.

**Comment by RohitSurwase** [comment]
There are no logs. handleSignInResult() function gets called inside onActivityResult if result is OK. But in sample app, after we launch SignInIntent there are no logs and all we can see is blank dialog as shown in earlier screenshot. And If I can cancel the dialog by tapping outside, it gives result CANCELED in onActivityResult.

**Comment by RohitSurwase** [comment]
@ammar-tesco  any update on the above issue?

**Comment by ammar-tesco** [comment]
> There are no logs. handleSignInResult() function gets called inside onActivityResult if result is OK. But in sample app, after we launch SignInIntent there are no logs and all we can see is blank dialog as shown in earlier screenshot. And If I can cancel the dialog by tapping outside, it gives result CANCELED in onActivityResult.

Seem like the sign in process is processing. If it success or error, it will return you a log as you can see  in the code.

There is a lot of possibility that can cause this, such as internet connection, Google play service on the phone is not up to date, Firewall on your network is blocked the connection, or you set up something in the Google API console wrongly, etc.

The Google sign-in part in out of our scope, since this part is provided by Google Auth API.

Anyhow, I also run the test of the sample app, there is no issues on my side.

**Comment by RohitSurwase** [comment]
> Seem like the sign in process is processing.

I have kept the device on that step for more than an hour still no progress.

> There is a lot of possibility that can cause this, such as internet connection, Google play service on the phone is not up to date, Firewall on your network is blocked the connection

I am getting same behavior on two devices and one which is pretty much clean, nothing else installed. Also, tried switch between WiFi and mobile data. Play service is up to date and no Firewall.

> The Google sign-in part in out of our scope, since this part is provided by Google Auth API.

Yes, I think the issue is with Drive API itself. I have seen similar issue on Google's Drive API sample app repo.

> I also run the test of the sample app, there is no issues on my side.

This makes me feel there is something wrong at my end. If you could, please share the sample app apk of yours with me so I can test it on my devices to confirm the issue is on my end. I hope you will not have any security concerns to share the apk as I dont have direct access to code.

Thanks so much for helping me so far. I really appreciate.

**Comment by ammar-tesco** [comment]
[app-release.apk.zip](https://github.com/ammarptn/GDrive-Rest-Android/files/5861531/app-release.apk.zip)

here is the apk file.

**Comment by RohitSurwase** [comment]
Thanks for sharing the apk. I tried the app after installing and here are my observations.
Devices
1. AVD with Play Services, Android 10
2. Galaxy M40, Android 10
3. AVD with Play Services, API 28

Observed behavior:
1. On all devices, after selecting account from chooser, something shows up for a moment and then I could see the email address at the bottom of the screen. 
2. None of the button in the app works.
3. If I go to Google Play Account to check for Connected Apps > out of 3 devices, 2 devices got Email and Profile Info access.
4. On one device, App did not have access to even Email and Profile Info.
5. None of the App has Google Drive access.

So, with this I can conclude that this library and sample apps does not work.
Thanks!

**Comment by ammar-tesco** [comment]
> Thanks for sharing the apk. I tried the app after installing and here are my observations.
> Devices
> 
> 1. AVD with Play Services, Android 10
> 2. Galaxy M40, Android 10
> 3. AVD with Play Services, API 28
> 
> Observed behavior:
> 
> 1. On all devices, after selecting account from chooser, something shows up for a moment and then I could see the email address at the bottom of the screen.
> 2. None of the button in the app works.
> 3. If I go to Google Play Account to check for Connected Apps > out of 3 devices, 2 devices got Email and Profile Info access.
> 4. On one device, App did not have access to even Email and Profile Info.
> 5. None of the App has Google Drive access.
> 
> So, with this I can conclude that this library and sample apps does not work.
> Thanks!

- If you ever read the code in the sample app that I provided in Github, you should know that all the button will only process the log. no other action after all.

- If you can see you an email address on the bottom, that mean the google login and the consent screen work normally. 
most of people stuck at this step cause they didn't config or wrongly config at the Google API Console.

- I already tested my sample app and also production app that use this Library, everything woking fine. So I can't agree that this library and sample apps does not work. you might config wrongly or didn't read the Google Drive API properly. 

Good luck

**Comment by RohitSurwase** [comment]
If the library/app has Google Drive access it should show up on Google Account under Connected Apps.
Look at the screenshot attached, it only has Email and Profile Info access. The apk that you have shared could be modified and it could be just signing in with Google account and not requesting the Drive access that is why it worked.
Don't close the issue in hurry. Thanks for helping so far.

<img width="362" alt="Screenshot 2021-01-24 at 10 02 20 AM" src="https://user-images.githubusercontent.com/22326509/105623054-a25d3c00-5e3c-11eb-8b7b-d666f29d68d2.png">
