### ISSUE TITLE
The download function returns meta and not the actual file

### ISSUE THREAD

**Issue by sabergeek** [ammarptn/GDrive-Rest-Android#2]
Hi there, 

Thanks for this library. I have a database upload and download feature in my app, where I upload the database to Google Drive (which works fine), and the user can download the same to restore backup (this no longer works after migration, I instead get a JSON file containing meta data). Is there any additional step required to use this metadata to retrieve the actual file?

**Comment by sabergeek** [comment]
Figured. The call is:

```
driveInstance.mDriveService.files()
                .get(fileId)
                .executeMedia().download(outputStream)
```
I wonder why this isn't included in any of the examples.

**Comment by ammarptn** [comment]
> Figured. The call is:
> 
> ```
> driveInstance.files()
>                 .get(fileId)
>                 .executeMedia().download(outputStream)
> ```
> 
> I wonder why this isn't included in any of the examples.

In order to download a file from Google drive, you can use this code.
`
mDriveServiceHelper.downloadFile(new java.io.File(getApplicationContext().getFilesDir(), "filename.txt"), "google_drive_file_id_here")
                        .addOnSuccessListener(new OnSuccessListener<Void>() {
                            @Override
                            public void onSuccess(Void aVoid) {

                            }
                        })
                        .addOnFailureListener(new OnFailureListener() {
                            @Override
                            public void onFailure(@NonNull Exception e) {

                            }
                        });
`
I already checked and it seems that I already included this code in the document and also an example in the code as well.
