### ISSUE TITLE
where to put .json file

### ISSUE THREAD

**Issue by harshadheaven** [ammarptn/GDrive-Rest-Android#20]
hello where to put .json file thst generate after SHA-1 signature filling

**Comment by ammar-tesco** [comment]
For Android app,
no need, just make sure that the package name and the SHA-1 signature of APK file match with the one that you fill in the Google Api console.

**Comment by ammarptn** [comment]
For Android app,
no need, just make sure that the package name and the SHA-1 signature of APK file match with the one that you fill in the Google Api console.
