### ISSUE TITLE
Struggling in setup process for sample app

### ISSUE THREAD

**Issue by java-crypto** [ammarptn/GDrive-Rest-Android#21]
I tried to run your sample app but I'm struggling in your command while installing:

**Step 5. Add "../auth/drive" in Scopes for Google APIs**

I could not find any point where to add the information. Can you kindly provide a screenshot from the Google Drive dashboard or somewhere where to edit the data, thanks?

Michael

**Comment by ammarptn** [comment]
@java-crypto 
Hi, seem like at the moment, google already update the setting menu to the new version.
Anyhow,
for step 5, you need to enter google api console (https://console.cloud.google.com/)
then select OAuth consent screen > prepare for verification
then fill the app detail and continue to the "scopes" tab
In the "scopes" tab, you will see a button -> "ADD OR REMOVE SCOPES" 
click at that button and select "../auth/drive"

![image](https://user-images.githubusercontent.com/4441622/132987935-1654c6f6-7e0d-4688-9f60-8dabcfda64cb.png)


this scope need to submit for review if you want to use it on production stage

**Comment by mshivamkumar** [comment]
How to upload, download whole folder not just a single file?
A problem is there it is uploading all files as excel files.

**Comment by ammarptn** [comment]
@mshivamkumar 
To upload a folder, you just create new folder on Google drive and loop the uploading one by one, same as downloading
