### ISSUE TITLE
Need help on mDriveServiceHelper.queryFiles()

### ISSUE THREAD

**Issue by ajinkya976** [ammarptn/GDrive-Rest-Android#3]
i want to return fileId when the filename  test_db. but in my case i am calling listFiles() method, first time after  Log.d(TAG, "Querying for files."); the code comes out of if condition and again it goes to  mDriveServiceHelper.queryFiles() and return the files. so when i am calling listFiles() method it returns empty fileid. please check logs below.
===========================================================
private String listFiles() {

        fileId="";
        if (mDriveServiceHelper != null) {
            Log.d(TAG, "Querying for files.");

            mDriveServiceHelper.queryFiles()
                    .addOnSuccessListener(fileList -> {
                        System.out.println(">>>>>>>>>>> Outside 1111 >>>>>>>>>>>>>>>> ");
                        //StringBuilder builder = new StringBuilder();
                        for (com.google.api.services.drive.model.File file : fileList.getFiles()) {
                           // builder.append(file.getName()).append("\n");
                            fileName=file.getName();

                            if(fileName.equals("test_db"))
                            {
                                fileId=file.getId();
                                System.out.println(">>>>>>>>>>> Outside >>>>>>> Id >>>>>>>>> "+fileId);
                            }

                           // System.out.println(">>>>>>>>>>> Outside >>>>>>>>>>>>"+fileName+" >>>>>>> Id >>>>>>>>> "+fileId);

                        }
                       // String fileNames = builder.toString();

                    })
                    .addOnFailureListener(exception -> Log.e(TAG, "Unable to query files.", exception));
        }
        System.out.println(">>>>>>>>>>> Outside >>>>>>>>>>>>"+fileName+" >>>>>>> Id >>>>>>>>> "+fileId);
        return fileId;
    }

=============================================================
                                                                     LOGS
=============================================================
09-03 23:04:55.155 21003-21003/com.example.mycuecards D/:::: Backup User Data ::::::::::: Querying for files.
09-03 23:04:55.165 21003-21003/com.example.mycuecards I/System.out: >>>>>>>>>>> Outside >>>>>>>>>>>>null >>>>>>> Id >>>>>>>>> 
09-03 23:04:55.165 21003-21003/com.example.mycuecards E/ZipFileCache: init failed when open zip file.
09-03 23:04:55.165 21003-21003/com.example.mycuecards E/ZipFileCache: init failed when open zip file.
09-03 23:04:55.165 21003-21003/com.example.mycuecards I/ViewRootImpl: CPU Rendering VSync enable = false
09-03 23:04:55.175 21003-21003/com.example.mycuecards I/View: ssignParent(ViewParent parent) parent is: android.view.ViewRootImpl@ad53f99
09-03 23:04:55.195 21003-21060/com.example.mycuecards E/HAL: hw_get_module_by_class: lib loaded: /system/lib/hw/gralloc.msm8916.so
09-03 23:04:55.255 21003-21382/com.example.mycuecards I/System: core_booster, getBoosterConfig = false
09-03 23:04:55.265 21003-21382/com.example.mycuecards I/System: core_booster, getBoosterConfig = false
09-03 23:04:55.975 21003-21003/com.example.mycuecards I/System.out: >>>>>>>>>>> Outside 1111 >>>>>>>>>>>>>>>> 
09-03 23:04:55.975 21003-21003/com.example.mycuecards I/System.out: >>>>>>>>>>> Outside >>>>>>> Id >>>>>>>>> 1GTGMZt86O6jR_CALCNAv5CDWZxuJ0BIj

==============================================================

please help on above .

Thanks in advance.

**Comment by ammarptn** [comment]
> # i want to return fileId when the filename test_db. but in my case i am calling listFiles() method, first time after Log.d(TAG, "Querying for files."); the code comes out of if condition and again it goes to mDriveServiceHelper.queryFiles() and return the files. so when i am calling listFiles() method it returns empty fileid. please check logs below.
> private String listFiles() {
> 
> ```
>     fileId="";
>     if (mDriveServiceHelper != null) {
>         Log.d(TAG, "Querying for files.");
> 
>         mDriveServiceHelper.queryFiles()
>                 .addOnSuccessListener(fileList -> {
>                     System.out.println(">>>>>>>>>>> Outside 1111 >>>>>>>>>>>>>>>> ");
>                     //StringBuilder builder = new StringBuilder();
>                     for (com.google.api.services.drive.model.File file : fileList.getFiles()) {
>                        // builder.append(file.getName()).append("\n");
>                         fileName=file.getName();
> 
>                         if(fileName.equals("test_db"))
>                         {
>                             fileId=file.getId();
>                             System.out.println(">>>>>>>>>>> Outside >>>>>>> Id >>>>>>>>> "+fileId);
>                         }
> 
>                        // System.out.println(">>>>>>>>>>> Outside >>>>>>>>>>>>"+fileName+" >>>>>>> Id >>>>>>>>> "+fileId);
> 
>                     }
>                    // String fileNames = builder.toString();
> 
>                 })
>                 .addOnFailureListener(exception -> Log.e(TAG, "Unable to query files.", exception));
>     }
>     System.out.println(">>>>>>>>>>> Outside >>>>>>>>>>>>"+fileName+" >>>>>>> Id >>>>>>>>> "+fileId);
>     return fileId;
> }
> ```
> 
> # =============================================================
> LOGS
> 09-03 23:04:55.155 21003-21003/com.example.mycuecards D/:::: Backup User Data ::::::::::: Querying for files.
> 09-03 23:04:55.165 21003-21003/com.example.mycuecards I/System.out: >>>>>>>>>>> Outside >>>>>>>>>>>>null >>>>>>> Id >>>>>>>>>
> 09-03 23:04:55.165 21003-21003/com.example.mycuecards E/ZipFileCache: init failed when open zip file.
> 09-03 23:04:55.165 21003-21003/com.example.mycuecards E/ZipFileCache: init failed when open zip file.
> 09-03 23:04:55.165 21003-21003/com.example.mycuecards I/ViewRootImpl: CPU Rendering VSync enable = false
> 09-03 23:04:55.175 21003-21003/com.example.mycuecards I/View: ssignParent(ViewParent parent) parent is: android.view.ViewRootImpl@ad53f99
> 09-03 23:04:55.195 21003-21060/com.example.mycuecards E/HAL: hw_get_module_by_class: lib loaded: /system/lib/hw/gralloc.msm8916.so
> 09-03 23:04:55.255 21003-21382/com.example.mycuecards I/System: core_booster, getBoosterConfig = false
> 09-03 23:04:55.265 21003-21382/com.example.mycuecards I/System: core_booster, getBoosterConfig = false
> 09-03 23:04:55.975 21003-21003/com.example.mycuecards I/System.out: >>>>>>>>>>> Outside 1111 >>>>>>>>>>>>>>>>
> 09-03 23:04:55.975 21003-21003/com.example.mycuecards I/System.out: >>>>>>>>>>> Outside >>>>>>> Id >>>>>>>>> 1GTGMZt86O6jR_CALCNAv5CDWZxuJ0BIj
> 
> ==============================================================
> 
> please help on above .
> 
> Thanks in advance.


from the code
```java
mDriveServiceHelper.queryFiles()
```
is Asynchronous function. 
While
```java
listFiles()
```
is Synchronous function
that is the reason that it will always return null

**Comment by ajinkya976** [comment]
> > ```java
> > private String listFiles() {
> > 
> > 
> >     fileId="";
> >     if (mDriveServiceHelper != null) {
> >         Log.d(TAG, "Querying for files.");
> > 
> >         mDriveServiceHelper.queryFiles()
> >                 .addOnSuccessListener(fileList -> {
> >                     System.out.println(">>>>>>>>>>> Outside 1111 >>>>>>>>>>>>>>>> ");
> >                     //StringBuilder builder = new StringBuilder();
> >                     for (com.google.api.services.drive.model.File file : fileList.getFiles()) {
> >                        // builder.append(file.getName()).append("\n");
> >                         fileName=file.getName();
> > 
> >                         if(fileName.equals("test_db"))
> >                         {
> >                             fileId=file.getId();
> >                             System.out.println(">>>>>>>>>>> Outside >>>>>>> Id >>>>>>>>> "+fileId);
> >                         }
> > 
> >                        // System.out.println(">>>>>>>>>>> Outside >>>>>>>>>>>>"+fileName+" >>>>>>> Id >>>>>>>>> "+fileId);
> > 
> >                     }
> >                    // String fileNames = builder.toString();
> > 
> >                 })
> >                 .addOnFailureListener(exception -> Log.e(TAG, "Unable to query files.", exception));
> >     }
> >     System.out.println(">>>>>>>>>>> Outside >>>>>>>>>>>>"+fileName+" >>>>>>> Id >>>>>>>>> "+fileId);
> >     return fileId;
> > }
> > ```
> > 
> > 
> > # =============================================================
> > LOGS
> > 09-03 23:04:55.155 21003-21003/com.example.mycuecards D/:::: Backup User Data ::::::::::: Querying for files.
> > 09-03 23:04:55.165 21003-21003/com.example.mycuecards I/System.out: >>>>>>>>>>> Outside >>>>>>>>>>>>null >>>>>>> Id >>>>>>>>>
> > 09-03 23:04:55.165 21003-21003/com.example.mycuecards E/ZipFileCache: init failed when open zip file.
> > 09-03 23:04:55.165 21003-21003/com.example.mycuecards E/ZipFileCache: init failed when open zip file.
> > 09-03 23:04:55.165 21003-21003/com.example.mycuecards I/ViewRootImpl: CPU Rendering VSync enable = false
> > 09-03 23:04:55.175 21003-21003/com.example.mycuecards I/View: ssignParent(ViewParent parent) parent is: android.view.ViewRootImpl@ad53f99
> > 09-03 23:04:55.195 21003-21060/com.example.mycuecards E/HAL: hw_get_module_by_class: lib loaded: /system/lib/hw/gralloc.msm8916.so
> > 09-03 23:04:55.255 21003-21382/com.example.mycuecards I/System: core_booster, getBoosterConfig = false
> > 09-03 23:04:55.265 21003-21382/com.example.mycuecards I/System: core_booster, getBoosterConfig = false
> > 09-03 23:04:55.975 21003-21003/com.example.mycuecards I/System.out: >>>>>>>>>>> Outside 1111 >>>>>>>>>>>>>>>>
> > 09-03 23:04:55.975 21003-21003/com.example.mycuecards I/System.out: >>>>>>>>>>> Outside >>>>>>> Id >>>>>>>>> 1GTGMZt86O6jR_CALCNAv5CDWZxuJ0BIj
> > ==============================================================
> > please help on above .
> > Thanks in advance.
> 
> from the code
> 
> ```java
> mDriveServiceHelper.queryFiles()
> ```
> 
> is Asynchronous function.
> While
> 
> ```java
> listFiles()
> ```
> 
> is Synchronous function
> that is the reason why it always return null

**Comment by ajinkya976** [comment]
Hi ammarptn ,

Can you please help me in above code. i want to return the fileid when we are calling the listfiles() in deltefiles() method.

So that i can delete file if it already exist.

Thanks in advance.

**Comment by ammarptn** [comment]
You can apply callback to the listfiles() function.
```java
interface onListFileListener{
public void onFound(String fileId);
public void onNotFound();
}
private void listFiles(String targetFileName, onListFileListener callback) {


    fileId="";
    if (mDriveServiceHelper != null) {
        Log.d(TAG, "Querying for files.");

        mDriveServiceHelper.queryFiles()
                .addOnSuccessListener(fileList -> {
                    System.out.println(">>>>>>>>>>> Outside 1111 >>>>>>>>>>>>>>>> ");
                    //StringBuilder builder = new StringBuilder();
                    for (com.google.api.services.drive.model.File file : fileList.getFiles()) {
                       // builder.append(file.getName()).append("\n");
                        fileName=file.getName();

                        if(fileName.equals(targetFileName))
                        {
                          callback.onFound(file.getId());
                            
                            System.out.println(">>>>>>>>>>> Outside >>>>>>> Id >>>>>>>>> "+fileId);
                        }
                        else{
                            callback.onNotFound();
                         }

                       // System.out.println(">>>>>>>>>>> Outside >>>>>>>>>>>>"+fileName+" >>>>>>> Id >>>>>>>>> "+fileId);

                    }
                   // String fileNames = builder.toString();

                })
                .addOnFailureListener(exception -> callback.onNotFound());
    }

  
}
```

I'm not yet testing the code above, use it at your own risk.....

**Comment by ajinkya976** [comment]
Thanks ammarptn i will try above code.

**Comment by ajinkya976** [comment]
i need one more. i am new to android and i have implemented google singin in my LoginActivity.java.

Now i want to drive rest api for upload, download etc.

Now to access drive rest api methods (upload, download etc) we are using below method first to create googleDriveService.

```
 private void requestSignIn() {
        Log.d(TAG, "Requesting sign-in");
        System.out.println(">>>>>>>>>> requestSignIn >>>>>>>>>>>>>");
        GoogleSignInOptions signInOptions =
                new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                        .requestEmail()
                        .requestScopes(new Scope(DriveScopes.DRIVE_FILE))
                        .build();
         googleSignInClient = GoogleSignIn.getClient(this, signInOptions);

        startActivityForResult(googleSignInClient.getSignInIntent(), REQUEST_CODE_SIGN_IN);
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent resultData) {

        System.out.println(">>>>>>>>>> onActivityResult >>>>>>>>>>>>>"+resultData);
        switch (requestCode) {
            case REQUEST_CODE_SIGN_IN:
                if (resultCode == Activity.RESULT_OK && resultData != null) {
                    handleSignInResult(resultData);
                }
                break;


        }

        super.onActivityResult(requestCode, resultCode, resultData);
    }
    String TAG = ":::: Backup User Data ::::::::::";
    private void handleSignInResult(Intent result) {
        GoogleSignIn.getSignedInAccountFromIntent(result)
                .addOnSuccessListener(googleAccount -> {
                    System.out.println(">>>>>>>>>>>> handleSignInResult inside Mainactivity>>>>>>>>>>>>>>>. ");
                    Log.d(TAG, "Signed in as " + googleAccount.getEmail());

                    // Use the authenticated account to sign in to the Drive service.
                    GoogleAccountCredential credential =
                            GoogleAccountCredential.usingOAuth2(
                                    this, Collections.singleton(DriveScopes.DRIVE_FILE));
                    credential.setSelectedAccount(googleAccount.getAccount());
                    Drive googleDriveService =
                            new Drive.Builder(
                                    AndroidHttp.newCompatibleTransport(),
                                    new GsonFactory(),
                                    credential)
                                    .setApplicationName("Drive API Migration")
                                    .build();

                    // The DriveServiceHelper encapsulates all REST API and SAF functionality.
                    // Its instantiation is required before handling any onClick actions.
                    mDriveServiceHelper = new DriveServiceHelper(googleDriveService);
                })
                .addOnFailureListener(exception -> Log.e(TAG, "Unable to sign in.", exception));
    }

```

Now in my case when i click on google login button in LoginActivity.java, i am getting **google select email address to login popup** and i am able to login successfully.

but once i logged-In i have written an Intent in LoginActivity.java which will send user to MainActivity.java (MainActivity.java contains upload, download etc functions).

Now the problem is, in MainActivity.java i am again calling  "startActivityForResult(googleSignInClient.getSignInIntent(), REQUEST_CODE_SIGN_IN);" to create      "mDriveServiceHelper = new DriveServiceHelper(googleDriveService);" so my code is again trying to open **google select email id popup** and it disappears.

Please help on above. actually i dont want to call "startActivityForResult(googleSignInClient.getSignInIntent(), REQUEST_CODE_SIGN_IN);" so that MainActivity.java will not try to open **google select email id popup** but if i am commenting that then i am getting null pointer exception on mDriveServiceHelper.

Please help on above.

**Comment by ammarptn** [comment]
If you already login. 
Call this function to retrieve GoogleSignInAccount object
```java
GoogleSignInAccount account = GoogleSignIn.getLastSignedInAccount(getApplicationContext());
	```
If it returns null, it mean you need to login again.
If not null then create mDriveServiceHelper

**Comment by ajinkya976** [comment]
Hi ammarptn... i written below code in MainActivity.java

 GoogleSignInAccount alreadyloggedAccount = GoogleSignIn.getLastSignedInAccount(this);
        if (alreadyloggedAccount != null) {
            //  Toast.makeText(this, "Already Logged In  Mainactivity...", Toast.LENGTH_SHORT).show();
            requestSignIn();
        } else {
            // Toast.makeText(this, "Not using google account...", Toast.LENGTH_SHORT).show();
            googlesignoutbtn.setVisibility(View.INVISIBLE);
            backup_data_button.setVisibility(View.INVISIBLE);
            restore_data_button.setVisibility(View.INVISIBLE);
        }

and  i am not getting null but i dont know how to proceed further. 
can you please help how to create googleDriveService for mDriveServiceHelper.

Thanks in advance.

**Comment by ajinkya976** [comment]
here is my MainActivity.java

=============================================================

```
package com.example.myplaycards;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.os.Environment;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.google.android.gms.auth.api.signin.GoogleSignIn;
import com.google.android.gms.auth.api.signin.GoogleSignInAccount;
import com.google.android.gms.auth.api.signin.GoogleSignInClient;
import com.google.android.gms.auth.api.signin.GoogleSignInOptions;
import com.google.android.gms.common.api.Scope;
import com.google.android.gms.drive.DriveId;
import com.google.android.gms.tasks.Continuation;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.android.gms.tasks.Task;
import com.google.api.client.extensions.android.http.AndroidHttp;
import com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential;
import com.google.api.client.json.gson.GsonFactory;
import com.google.api.services.drive.Drive;
import com.google.api.services.drive.DriveScopes;
import com.google.gson.Gson;

import java.io.File;
import java.util.Collections;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    private TextView viewCardButton,createDeckButton;
    private Toolbar mToolbar;
    private ImageView googlesignoutbtn;
    private GoogleSignInClient googleSignInClient;
    private Button backup_data_button,restore_data_button;
    private DriveServiceHelper mDriveServiceHelper;
    public static final String PACKAGE_NAME = "com.example.myplaycards";
    public static final String DATABASE_NAME = "play_cards_db";
    public static final String TABLE_NAME = "play_cards_db";
    private static final String DATABASE_PATH = "/data/data/" + PACKAGE_NAME + "/databases/" + DATABASE_NAME;
    private static final File DATA_DIRECTORY_DATABASE =new File(Environment.getDataDirectory() + "/data/" + PACKAGE_NAME + "/databases/" + DATABASE_NAME);
    String fileId,fileName;
    private static final int REQUEST_CODE_SIGN_IN = 1;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        viewCardButton=findViewById(R.id.view_card);
        createDeckButton=findViewById(R.id.card_deck);
        googlesignoutbtn=findViewById(R.id.google_signout_btn);
        backup_data_button=findViewById(R.id.backup_data_button);
        restore_data_button=findViewById(R.id.restore_data_button);

        mToolbar = findViewById(R.id.main_acitvity_toolbar);
        setSupportActionBar(mToolbar);
        getSupportActionBar().setTitle("play Cards");

        GoogleSignInAccount alreadyloggedAccount = GoogleSignIn.getLastSignedInAccount(this);
        if (alreadyloggedAccount != null) {
            //  Toast.makeText(this, "Already Logged In  Mainactivity...", Toast.LENGTH_SHORT).show();
            requestSignIn();
        } else {
            // Toast.makeText(this, "Not using google account...", Toast.LENGTH_SHORT).show();
            googlesignoutbtn.setVisibility(View.INVISIBLE);
            backup_data_button.setVisibility(View.INVISIBLE);
            restore_data_button.setVisibility(View.INVISIBLE);
        }

       // GoogleSignInAccount account =getIntent().getParcelableExtra("ACCOUNT");



        viewCardButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(MainActivity.this, ListDecks.class);
                intent.addFlags( Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
                startActivity(intent);
            }
        });

        createDeckButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(MainActivity.this, CreateDeck.class);
                intent.addFlags( Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
                intent.putExtra("deckname","Enter Deck Name...");
                intent.putExtra("functionname","Function Name...");
                startActivity(intent);
            }
        });


        googlesignoutbtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
          /*
          Sign-out is initiated by simply calling the googleSignInClient.signOut API. We add a
          listener which will be invoked once the sign out is the successful
           */
                googleSignInClient.signOut().addOnCompleteListener(new OnCompleteListener<Void>() {
                    @Override
                    public void onComplete(@NonNull Task<Void> task) {
                        //On Succesfull signout we navigate the user back to LoginActivity
                        Intent intent=new Intent(MainActivity.this,LoginActivity.class);
                        intent.addFlags( Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
                        startActivity(intent);
                    }
                });
            }
        });



        backup_data_button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

               // uploadFile();
                uploadFile();
                Toast.makeText(MainActivity.this, "Data Backup Started....", Toast.LENGTH_SHORT).show();

                /*Intent intent=new Intent(MainActivity.this,CloudBackup.class);
                intent.addFlags( Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
                startActivity(intent);*/


            }
        });

        restore_data_button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                System.out.println(">>>>>>>>>> sending to create file>>>>>>>>>>>>>");
                downoadFile();
                /*Intent intent=new Intent(MainActivity.this,BackupDBToDrive.class);
                intent.addFlags( Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
                startActivity(intent);*/
            }
        });

    }

    private void requestSignIn() {
        Log.d(TAG, "Requesting sign-in");
        System.out.println(">>>>>>>>>> requestSignIn >>>>>>>>>>>>>");
        GoogleSignInOptions signInOptions =
                new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                        .requestEmail()
                        .requestScopes(new Scope(DriveScopes.DRIVE_FILE))
                        .build();
         googleSignInClient = GoogleSignIn.getClient(this, signInOptions);

        // The result of the sign-in Intent is handled in onActivityResult.
        startActivityForResult(googleSignInClient.getSignInIntent(), REQUEST_CODE_SIGN_IN);
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent resultData) {

        System.out.println(">>>>>>>>>> onActivityResult >>>>>>>>>>>>>"+resultData);
        switch (requestCode) {
            case REQUEST_CODE_SIGN_IN:
                if (resultCode == Activity.RESULT_OK && resultData != null) {
                    handleSignInResult(resultData);
                }
                break;


        }

        super.onActivityResult(requestCode, resultCode, resultData);
    }
    String TAG = ":::: Backup User Data ::::::::::";
    private void handleSignInResult(Intent result) {
        GoogleSignIn.getSignedInAccountFromIntent(result)
                .addOnSuccessListener(googleAccount -> {
                    System.out.println(">>>>>>>>>>>> handleSignInResult inside Mainactivity>>>>>>>>>>>>>>>. ");
                    Log.d(TAG, "Signed in as " + googleAccount.getEmail());

                    // Use the authenticated account to sign in to the Drive service.
                    GoogleAccountCredential credential =
                            GoogleAccountCredential.usingOAuth2(
                                    this, Collections.singleton(DriveScopes.DRIVE_FILE));
                    credential.setSelectedAccount(googleAccount.getAccount());
                    Drive googleDriveService =
                            new Drive.Builder(
                                    AndroidHttp.newCompatibleTransport(),
                                    new GsonFactory(),
                                    credential)
                                    .setApplicationName("Drive API Migration")
                                    .build();

                    // The DriveServiceHelper encapsulates all REST API and SAF functionality.
                    // Its instantiation is required before handling any onClick actions.
                    mDriveServiceHelper = new DriveServiceHelper(googleDriveService);
                })
                .addOnFailureListener(exception -> Log.e(TAG, "Unable to sign in.", exception));
    }


    private void uploadFile() {

         mDriveServiceHelper.searchFile("play_cards_db","application/x-sqlite-3")
                    .continueWithTask(new Continuation<GoogleDriveFileHolder, Task<Void>>(){
                        @Override
                        public Task<Void> then(@NonNull Task<GoogleDriveFileHolder> task) throws Exception {
                            System.out.println(":::::::::Old file deleted successfuly....:::::::::::::::"+task.getResult().getId());
                            return mDriveServiceHelper.deleteFolderFile(task.getResult().getId());
                        }
                    });


        if (mDriveServiceHelper != null) {
            Log.d(TAG, "Creating a file.");

            mDriveServiceHelper.uploadFile(DATA_DIRECTORY_DATABASE,"application/x-sqlite-3",null)
                    .addOnSuccessListener(new OnSuccessListener<GoogleDriveFileHolder>() {
                        @Override
                        public void onSuccess(GoogleDriveFileHolder googleDriveFileHolder) {
                            Gson gson = new Gson();
                            Log.d(TAG, "onSuccess: " + gson.toJson(googleDriveFileHolder));
                        }
                    })
                    .addOnFailureListener(new OnFailureListener() {
                        @Override
                        public void onFailure(@NonNull Exception e) {
                            Log.d(TAG, "onFailure: " + e.getMessage());
                        }
                    });
        }
    }

    public void downoadFile()
    {
        if (mDriveServiceHelper != null) {
            Log.d(TAG, "Querying for files.");

            mDriveServiceHelper.queryFiles()
                    .addOnSuccessListener(fileList -> {
                        //StringBuilder builder = new StringBuilder();
                        for (com.google.api.services.drive.model.File file : fileList.getFiles()) {
                            // builder.append(file.getName()).append("\n");
                            fileName=file.getName();

                            if(fileName.equals("play_cards_db"))
                            {
                                fileId=file.getId();

                                mDriveServiceHelper.downloadFile(new File("/data/data/com.example.myplaycards/databases/play_cards_db"), fileId)
                                        .addOnSuccessListener(new OnSuccessListener<Void>() {
                                            @Override
                                            public void onSuccess(Void aVoid) {
                                                Toast.makeText(MainActivity.this, "Backup Done...", Toast.LENGTH_SHORT).show();
                                            }
                                        })
                                        .addOnFailureListener(new OnFailureListener() {
                                            @Override
                                            public void onFailure(@NonNull Exception e) {

                                            }
                                        });
                            }

                            // System.out.println(">>>>>>>>>>> Outside >>>>>>>>>>>>"+fileName+" >>>>>>> Id >>>>>>>>> "+fileId);

                        }
                        // String fileNames = builder.toString();

                    })
                    .addOnFailureListener(exception -> Log.e(TAG, "Unable to query files.", exception));
        }


    }


    private void readFile(String fileId) {
        if (mDriveServiceHelper != null) {
            Log.d(TAG, "Reading file " + fileId);

            mDriveServiceHelper.readFile(fileId)
                    .addOnSuccessListener(nameAndContent -> {
                        String name = nameAndContent.first;
                        String content = nameAndContent.second;

                      //  mFileTitleEditText.setText(name);
                      //  mDocContentEditText.setText(content);

                        setReadWriteMode(fileId);
                    })
                    .addOnFailureListener(exception ->
                            Log.e(TAG, "Couldn't read file.", exception));
        }
    }

    String mOpenFileId;
    private void setReadWriteMode(String fileId) {
       // mFileTitleEditText.setEnabled(true);
        //mDocContentEditText.setEnabled(true);
        mOpenFileId = fileId;
    }

    private void deleteDriveFile(String GoogleFileId) {
        mDriveServiceHelper.deleteFolderFile(GoogleFileId).addOnSuccessListener(new OnSuccessListener<Void>() {
            @Override
            public void onSuccess(Void aVoid) {

            }
        }).addOnFailureListener(new OnFailureListener() {
            @Override
            public void onFailure(@NonNull Exception e) {

            }
        });
    }



   /* private String listFiles() {

        fileId="";
        if (mDriveServiceHelper != null) {
            Log.d(TAG, "Querying for files.");

            mDriveServiceHelper.queryFiles()
                    .addOnSuccessListener(fileList -> {
                        System.out.println(">>>>>>>>>>> Outside 1111 >>>>>>>>>>>>>>>> ");
                        //StringBuilder builder = new StringBuilder();
                        for (com.google.api.services.drive.model.File file : fileList.getFiles()) {
                           // builder.append(file.getName()).append("\n");
                            fileName=file.getName();

                            if(fileName.equals("play_cards_db"))
                            {
                                fileId=file.getId();
                                System.out.println(">>>>>>>>>>> Outside >>>>>>> Id >>>>>>>>> "+fileId);
                            }

                           // System.out.println(">>>>>>>>>>> Outside >>>>>>>>>>>>"+fileName+" >>>>>>> Id >>>>>>>>> "+fileId);

                        }
                       // String fileNames = builder.toString();

                    })
                    .addOnFailureListener(exception -> Log.e(TAG, "Unable to query files.", exception));
        }
        System.out.println(">>>>>>>>>>> Outside >>>>>>>>>>>>"+fileName+" >>>>>>> Id >>>>>>>>> "+fileId);
        return fileId;
    }
*/

}
```

**Comment by ajinkya976** [comment]
Hi ammarptn,

Thanks for your help. i have created it successfully.
