### ISSUE TITLE
How to create nested folders?

### ISSUE THREAD

**Issue by mjavadf** [ammarptn/GDrive-Rest-Android#4]
how can I create a folder inside another folder? can you explain to me plz?
I can't understand how to use `searchFolder()` and how to pass the result to `createFolder()`

**Comment by ammarptn** [comment]
> how can I create a folder inside another folder? can you explain to me plz?
> I can't understand how to use `searchFolder()` and how to pass the result to `createFolder()`

Step 1 : you have to use searchFolder() and it will return googleDriveFileHolders
Step 2 : you can get folderID from googleDriveFileHolders.getId();
Step 3: use createFolder("folderName","folderID") then it will create new folder inside
